### ISSUE TITLE
Orden Canvas leap y kinect/Pausa

### ISSUE THREAD

**Issue by andresow** [MCV-Univalle/Playtherapy#102]
El canvas debe ir adelante del panel de pausa

**Comment by andresow** [comment]
Se realiza el ordenamiento del panel de dispositivo en los minijuegos(panel antes que parametros)
Se adjunta evidencia en algunos juegos
![image.png](https://images.zenhubusercontent.com/5d14dd72b4a18a460a8e2f5d/8dfbf507-3a0e-4b8c-b2a6-8a33ffdf7021)
![image.png](https://images.zenhubusercontent.com/5d14dd72b4a18a460a8e2f5d/082f4c4b-f88f-46f0-beaa-b576b03949b9)
![image.png](https://images.zenhubusercontent.com/5d14dd72b4a18a460a8e2f5d/904d7d3b-0019-47ac-87f3-413fc3973a5a)
![image.png](https://images.zenhubusercontent.com/5d14dd72b4a18a460a8e2f5d/6c0564d2-acda-4475-ba69-48ad0986f852)

**Comment by melissamillares** [comment]
Revisado.
