### ISSUE TITLE
Revisar ortografia

### ISSUE THREAD

**Issue by andresow** [MCV-Univalle/Playtherapy#108]

**Comment by andresow** [comment]
Revisar tipografía de Baseball en el tutorial

**Comment by melissamillares** [comment]
Revisar ortografía y tipografía en todos los juegos.

**Comment by jpcv222** [comment]
Se encontraron las siguientes correcciones ortográficas por realizar **Error [Corrección]**
## Menú de pausa
- Mensaje de diálogo de confirmación opción Reiniciar juego: "**¿Esta [Está]** seguro que desea reiniciar el juego?"
- Mensaje de diálogo de confirmación opción Menú principal: "**¿Esta [Está]** seguro que desea volver al **Menu [Menú]** principal?**.[]**"
- Mensaje de diálogo de confirmación opción Cerrar sesión: "**¿Esta [Está]** seguro que desea finalizar **sesion [sesión]**?"
- Opciones de diálogo de confirmación opción Reiniciar juego; Menú principal; Cerrar sesión: "**Si [Sí]**".
- Botón  de opción "**Menu [Menú]** principal".

**Comment by melissamillares** [comment]
Revisado.
