### ISSUE TITLE
Respuesta de juego cuando no hay animales

### ISSUE THREAD

**Issue by jpcv222** [MCV-Univalle/Playtherapy#111]
Averiguar qué pasa cuando se llevan todos los animales
NOTA: Validar con el grupo qué debería pasar

**Comment by edwingamboa** [comment]
Cuál es la evidencia de cumplimiento?

**Comment by andresow** [comment]
De acuerdo a las configuraciones no es posible tener menos animales que la cantidad de naves que llegan.
![image.png](https://images.zenhubusercontent.com/5d14dd72b4a18a460a8e2f5d/c2eb502a-c2a1-4e3b-9b75-5504a94c7072)
