### ISSUE TITLE
Tiempo de juego

### ISSUE THREAD

**Issue by jpcv222** [MCV-Univalle/Playtherapy#116]
Asegurar que el juego dure el tiempo programado en la pantalla de parámetros

**Comment by andresow** [comment]
El tiempo de juego no se cumplía en el caso que las naves se comieran todos los animales, para esto se añaden mas animales de manera dinámica con el tiempo. Añadiendo hasta 40 animales mas para poder jugar completamente 

https://drive.google.com/open?id=1-mlF6Fb6tpshEz6FTv_V_97_BuIvpfP6

![image.png](https://images.zenhubusercontent.com/5d14dd72b4a18a460a8e2f5d/e313488f-8709-438d-be29-f81d30831536)

**Comment by melissamillares** [comment]
Revisado.
