### ISSUE TITLE
Reinicio del juego

### ISSUE THREAD

**Issue by jpcv222** [MCV-Univalle/Playtherapy#127]
Al reiniciar y configurar el juego deben volver a aparecer los topos y no perder los puntos ya ganados

**Comment by andresow** [comment]
@jpcv222 @edwingamboa  Pienso que debería de perder los puntos, no tiene sentido reiniciar el juego en ese caso.

**Comment by jpcv222** [comment]
[Vídeo de prueba](https://drive.google.com/open?id=1LHL3xF9Sa8MImy1lX4UX3s7MIksex2oA)

**Comment by melissamillares** [comment]
Revisado.
Creo que el cuadro que se muestra debería tener la misma tipografía y estilo de los botones. Esta frase no debe terminar en punto, porque el signo de pregunta ya lo contiene. 

![image](https://user-images.githubusercontent.com/26610889/78917533-97275400-7a54-11ea-8959-a92701f8eae5.png)
