### ISSUE TITLE
Área de juego

### ISSUE THREAD

**Issue by jpcv222** [MCV-Univalle/Playtherapy#128]
Establecer un área física de juego más adecuada, delimitando el alcance ideal del Leap

**Comment by jpcv222** [comment]
Aplicar indicaciones realizadas por terapeuta: Medir área adecuada para juego en posición cruzada o diagonal.

**Comment by andresow** [comment]
Tomar foto de la zona

**Comment by melissamillares** [comment]
Adjuntar evidencia de la solución.

**Comment by jpcv222** [comment]
![area_juego_leap.jpg](https://images.zenhubusercontent.com/5d1d50c49c916c09a936e985/0b9dfa21-e79f-4de4-a3fe-89b65cfc9937)

**Comment by jpcv222** [comment]
![areajuego.png](https://images.zenhubusercontent.com/5d1d50c49c916c09a936e985/cc8fdf01-c219-4097-94c5-a87d6b718a2c)
