### ISSUE TITLE
Distribuciones de los huecos

### ISSUE THREAD

**Issue by jpcv222** [MCV-Univalle/Playtherapy#129]
Ofrecer 3 distribuciones de los huecos de los topos predefinidas, cada una con una dificultad diferente, para que el terapeuta tenga varias opciones qué ofrecer

**Comment by andresow** [comment]
![image.png](https://images.zenhubusercontent.com/5d14dd72b4a18a460a8e2f5d/13d99537-e675-4f06-8e6b-643aa5e96603)
