### ISSUE TITLE
Pérdida de puntos

### ISSUE THREAD

**Issue by jpcv222** [MCV-Univalle/Playtherapy#130]
Previo al juego, indicar en el tutorial cuándo se pierden puntos

**Comment by jpcv222** [comment]
Se añade en el tutorial, una pantalla adicional  en el tutorial
![image.png](https://images.zenhubusercontent.com/5d1d50c49c916c09a936e985/d1ead188-a42f-42f5-af60-9f52c58853dc)

**Comment by edwingamboa** [comment]
Error en el mensaje.  "cada que un tope se escapa", -> "cada que un topo se escapa"

**Comment by andresow** [comment]
![image.png](https://images.zenhubusercontent.com/5d14dd72b4a18a460a8e2f5d/24ca4529-ec62-4031-9724-b1611ab01720)
