### ISSUE TITLE
Banner negro con mucha transparencia para los logos

### ISSUE THREAD

**Issue by edwingamboa** [MCV-Univalle/Playtherapy#138]

**Comment by melissamillares** [comment]
Adjuntar evidencia de la solución.

**Comment by jpcv222** [comment]
Versión actual de logos:
![image.png](https://images.zenhubusercontent.com/5d1d50c49c916c09a936e985/6f68e64b-5b6a-41ca-9f58-358810454f51)

**Comment by melissamillares** [comment]
Revisado.
