### ISSUE TITLE
Instrucciones para terapeutas

### ISSUE THREAD

**Issue by andresow** [MCV-Univalle/Playtherapy#140]
Se debe añadir al final de los tutoriales una explicación corta de cada uno de los parámetros, esto para que el terapeuta también tenga un minitutorial

**Comment by edwingamboa** [comment]
@andresow por favor ser un poco más específico en la descripción del issue

**Comment by melissamillares** [comment]
Adjuntar evidencia de la solución.

**Comment by andresow** [comment]
Aparatado de instrucciones para terapeutas, se adjuntan evidencia de algunos juegos.

![image.png](https://images.zenhubusercontent.com/5d14dd72b4a18a460a8e2f5d/119b70c6-0d72-4596-b5bb-4885d449f0d6)
![image.png](https://images.zenhubusercontent.com/5d14dd72b4a18a460a8e2f5d/eb2caf0e-acfd-43d8-9344-82d56c5e7ba6)

**Comment by melissamillares** [comment]
Revisado.
Recuerden revisar la ortografía.
