### ISSUE TITLE
Modificar opciones de diálogo de confirmación

### ISSUE THREAD

**Issue by jpcv222** [MCV-Univalle/Playtherapy#146]
Los diálogos de confirmación deben tener como opción de respuesta en sus botones "Sí" y "No". Actualmente tienen "Aceptar" y "Cancelar".

**Comment by andresow** [comment]
Se cambia los diálogos de confirmación a si y no en todos los puntos correspondientes. Se añaden fotos de algunos puntos en diferentes juegos

![image.png](https://images.zenhubusercontent.com/5d14dd72b4a18a460a8e2f5d/38e45ffe-f141-4818-ae17-a9ccc0a47a17)

![image.png](https://images.zenhubusercontent.com/5d14dd72b4a18a460a8e2f5d/217ff996-c48e-4f0d-b458-d7a2d9e0df3f)

![image.png](https://images.zenhubusercontent.com/5d14dd72b4a18a460a8e2f5d/5ddb279b-6d4c-4aa3-9172-bbdb28c965ad)
