### ISSUE TITLE
Tutorial de parámetros

### ISSUE THREAD

**Issue by jpcv222** [MCV-Univalle/Playtherapy#147]
Los tutoriales donde se explican los parámetros deberían diferenciar visualmente el nombre del parámetro de la descripción. Se propone realizarlo con un salto de línea.

**Comment by andresow** [comment]
Se realiza el santo de linea sugerido para diferenciar el titulo con su explicacion
![image.png](https://images.zenhubusercontent.com/5d14dd72b4a18a460a8e2f5d/c786468a-9bdd-4cfe-b4c4-48fcc7a7771c)

**Comment by melissamillares** [comment]
Revisado.
