### ISSUE TITLE
Modificar apariencia de logos

### ISSUE THREAD

**Issue by jpcv222** [MCV-Univalle/Playtherapy#149]
Se debe idear una estrategia para mejorar la presentación de los logos de instituciones u organizaciones involucradas en el proyecto Playtherapy.

**Comment by andresow** [comment]
![image.png](https://images.zenhubusercontent.com/5d14dd72b4a18a460a8e2f5d/b8c17bda-c5ef-4c9a-85c6-74000aa560dc)
