### ISSUE TITLE
Botón "Menú principal" sin diálogo de confirmación.

### ISSUE THREAD

**Issue by jpcv222** [MCV-Univalle/Playtherapy#151]
El botón "Menú principal" del menú de pausa no tiene diálogo de confirmación. 
Deberá aparecer el diálogo de confirmación con el mensaje "¿Está seguro que desea volver al menú principal?" al dar click sobre el botón "Menú principal" que se muestra en la imagen adjunta. ![dialogo_menu.PNG](https://images.zenhubusercontent.com/5d1d50c49c916c09a936e985/66a1f762-3367-49da-bfb2-ebd577bbd0b1)

**Comment by andresow** [comment]
Imagen de prueba: ![image.png](https://images.zenhubusercontent.com/5d14dd72b4a18a460a8e2f5d/406774da-e9d7-4491-a729-4de9d283ec5d)
