### ISSUE TITLE
Configuración de parámetros en modo repeticiones.

### ISSUE THREAD

**Issue by jpcv222** [MCV-Univalle/Playtherapy#153]
La configuración en modo **repeticiones** del juego **Rieles** no debe ser posible si solo se añade el parámetro **trote**.

**Comment by jpcv222** [comment]
Se prueba la configuración y se encuentra que el juego no finaliza. El jugador solo trota, sin obstáculos, por lo que las repeticiones no se controlan.

**Comment by andresow** [comment]
Se limita el modo de juego a **Tiempo** si no hay **Sentadillas** o **Saltos**
![image.png](https://images.zenhubusercontent.com/5d14dd72b4a18a460a8e2f5d/2e06fea8-3143-4def-bde7-af44999de005)
