### ISSUE TITLE
Configuración de parámetros en modo tiempo.

### ISSUE THREAD

**Issue by jpcv222** [MCV-Univalle/Playtherapy#154]
Si en modo **tiempo** se configura solamente el parámetro **trote**, no tiene sentido configurar la **dificultad del juego**.

**Comment by andresow** [comment]
Se bloquea parámetro **dificultad de juego**, si en modo **Tiempo** no se configura el juego para que vengan obstáculos (solo trote).
![image.png](https://images.zenhubusercontent.com/5d14dd72b4a18a460a8e2f5d/766bed7d-232f-412f-a404-fcdf28c88eda)
