### ISSUE TITLE
"Movimiento lateral" deshabilita "Alcance"

### ISSUE THREAD

**Issue by jpcv222** [MCV-Univalle/Playtherapy#155]
Si se configura el parámetro "Movimiento lateral", el parámetro "Alcance" no tiene sentido que se pueda modificar. Debe deshabilitarse (por defecto sin selección).

**Comment by andresow** [comment]
**Movimiento lateral** deshabilita **Alcance**.
Prueba deshabilitando:
![image.png](https://images.zenhubusercontent.com/5d14dd72b4a18a460a8e2f5d/41d44bff-b3b6-47df-9ad6-383709c49154)
Prueba habilitando: 
![image.png](https://images.zenhubusercontent.com/5d14dd72b4a18a460a8e2f5d/93edf13f-96f3-4d25-bbe7-2da1e764ce08)
