### ISSUE TITLE
Configuración de ángulos

### ISSUE THREAD

**Issue by jpcv222** [MCV-Univalle/Playtherapy#156]
Al configurar los ángulos de movimiento en el juego, se debe garantizar que se cumpla: 

- "Ángulo máximo" debe ser mayor a "Ángulo mínimo". 
- No debería ser posible que ambos  "Ángulo máximo" y "Ángulo mínimo" sean igual a cero.
- "Ángulo máximo" no debería ser igual a cero en ningún caso.

**Comment by andresow** [comment]
![image.png](https://images.zenhubusercontent.com/5d14dd72b4a18a460a8e2f5d/f53da3ae-5d17-4b25-b4c8-5291a17f133e)

Vídeo en: https://drive.google.com/open?id=1cXejPmBWKtLQXgPqV_RYf5B1k5QxmB2t
