### ISSUE TITLE
Comportamiento erróneo de checkbox

### ISSUE THREAD

**Issue by melissamillares** [MCV-Univalle/Playtherapy#166]
En el juego Fight, al seleccionar opción **Flexión y Abducción** se habilita la opción **Extensión**

**Comment by jpcv222** [comment]
Se actualizan los checkbox de tipo de movimienti (Flexión, Extensión, Flexión y Abducción). Vídeo de prueba: [https://cutt.ly/EyUMGkF](https://cutt.ly/EyUMGkF)

**Comment by franco026** [comment]
Revisado
