### ISSUE TITLE
Orden de opciones de pantalla de pausa

### ISSUE THREAD

**Issue by jpcv222** [MCV-Univalle/Playtherapy#167]
Se debe cambiar el orden de las opciones de la pantalla de pausa a:

- Seguir
- Tutorial
- Reiniciar juego
- Menú principal
- Cerrar sesión

**Comment by jpcv222** [comment]
**Vecinos invasores**
![image.png](https://images.zenhubusercontent.com/5d1d50c49c916c09a936e985/e4d9cbd6-bc70-43bd-bb5a-f5c835600698)
**Tiro libre**
![image.png](https://images.zenhubusercontent.com/5d1d50c49c916c09a936e985/05daa5a8-62d0-485c-ac11-fa018bd3d5a3)
**Vecinos invasores**
![image.png](https://images.zenhubusercontent.com/5d1d50c49c916c09a936e985/a9994928-2b14-4ba6-8dee-8797eaaa8bc3)

**Comment by franco026** [comment]
Revisado
