### ISSUE TITLE
Uso de nuevo template con derechos de autoría necesario

### ISSUE THREAD

**Issue by andresow** [MCV-Univalle/Playtherapy#170]
El web admin actualmente no cuenta con los derechos que se deben dar por el uso del template, se debe buscar un nuevo template para django 2 y adaptarlo correctamente

**Comment by andresow** [comment]
Dentro del template se deja un footer dando los derechos de autor necesarios
![image.png](https://images.zenhubusercontent.com/5d14dd72b4a18a460a8e2f5d/cda8eb4b-d5db-4c51-a0b5-c8d746b38223)

**Comment by melissamillares** [comment]
Revisado.
