### ISSUE TITLE
Adaptar reportes por tablas con filtros de busquedad

### ISSUE THREAD

**Issue by andresow** [MCV-Univalle/Playtherapy#171]
Debido a que Luis propone como reporte tener un registro en formato de tabla de las veces que a jugado y con información con puntajes, se pasa a adaptar el uso de las librerías DataTable.

**Comment by andresow** [comment]
Juan Pablo proporciona la libreria correspondiente y se pasa a adaptar el uso de esta, actualmente esta implementada para listar usuarios y pacientes.
![image.png](https://images.zenhubusercontent.com/5d14dd72b4a18a460a8e2f5d/67639afc-bded-47a3-babb-03e86a490802)

**Comment by melissamillares** [comment]
Revisado.
