### ISSUE TITLE
Se debe dar la posibilidad de crear entidades medicas, diagnósticos y tipos de diagnosticos 

### ISSUE THREAD

**Issue by andresow** [MCV-Univalle/Playtherapy#172]

**Comment by andresow** [comment]
![image.png](https://images.zenhubusercontent.com/5d14dd72b4a18a460a8e2f5d/fcb9b42d-57ca-4614-aa84-15af19f5770b)

![image.png](https://images.zenhubusercontent.com/5d14dd72b4a18a460a8e2f5d/0e1f3f18-a4fc-4233-a7fb-c2c7ae11ddee)

**Comment by melissamillares** [comment]
Revisado.
