### ISSUE TITLE
Añadir nuevo campo al registro de terapeuta

### ISSUE THREAD

**Issue by andresow** [MCV-Univalle/Playtherapy#173]
Debido a que hora es posible que PlayTherapy es de uso tanto para Fisioterapeutas, como para Terapeutas ocupacionales, se añade dicha opción al modelo y por ende al registro

**Comment by andresow** [comment]
![image.png](https://images.zenhubusercontent.com/5d14dd72b4a18a460a8e2f5d/1afb96d7-66ec-485f-8b99-55b57a2cbf99)

**Comment by melissamillares** [comment]
Revisado.
