### ISSUE TITLE
Área de juego Leap Motion

### ISSUE THREAD

**Issue by jpcv222** [MCV-Univalle/Playtherapy#175]
Establecer un área física de juego más adecuada, delimitando el alcance ideal del Leap. Debe haber formato digital del área física (imagen).

**Comment by jpcv222** [comment]
![areajuego.png](https://images.zenhubusercontent.com/5d1d50c49c916c09a936e985/18bcefa0-b023-472f-aab4-509faf4df2d1)

**Comment by melissamillares** [comment]
Revisado.
