### ISSUE TITLE
Evaluación de herramienta Teachable Machine

### ISSUE THREAD

**Issue by jpcv222** [MCV-Univalle/Playtherapy#176]
Evaluar rangos de la herramienta Teachable Machine y exponer si nos sirve para fines de reconocimiento y correctitud de movimientos.

**Comment by mgcc05** [comment]
La herramienta Teachable Machine no reconoce movimientos específicos de las manos, por lo tanto, solo nos serviría para movimientos que impliquen todo el miembro superior, inferior o cuerpo completo, con los rangos en 40° alejándose de la linea media para miembro inferior, y en miembro superior a 180°, sentadillas, saltos, siendo útil para juegos como rieles, gran viaje, pero no será viable utilizarlo en los juegos como piano, topos, entre otros que impliquen movimientos de mano y dedos.

**Comment by mgcc05** [comment]
[Teachable Machine](https://drive.google.com/open?id=1uMd0Bv3g80QJIYUXwRRk0xWQoQjn-bYz)

**Comment by melissamillares** [comment]
Revisado.
