### ISSUE TITLE
Atributo score y level de relación start_session

### ISSUE THREAD

**Issue by jpcv222** [MCV-Univalle/Playtherapy#177]
Se debe clarificar lo que se guarda en los atributos **score** y **level** de la relación **start_session** en la base de datos.

**Comment by jpcv222** [comment]
Se revisan archivos GameManager de cada juego, así como también Scripts de la carpeta [DAO](https://github.com/MCV-Univalle/Playtherapy/blob/master/Playtherapy/Assets/Scripts/DAO). Se identifica:

1. Cada juego cuenta en su script GameManager con las siguientes tres variables:
- score: Según los Scripts, **score** es el resultado de la operación **puntos buenos** menos **puntos malos** (cero si ese resultado es negativo). Ejemplo: [Piano](https://github.com/MCV-Univalle/Playtherapy/blob/c988e064259631f59331705f30ce55e2695f120b/Playtherapy/Assets/Scripts/Piano/GameManagerPiano.cs#L208-L209).
- fullScore: De acuerdo al código, **fullScore** representa la cantidad de puntos buenos realizados.  Ejemplo: [Piano](https://github.com/MCV-Univalle/Playtherapy/blob/c988e064259631f59331705f30ce55e2695f120b/Playtherapy/Assets/Scripts/Piano/GameManagerPiano.cs#L216-L217).
- finalScore: Representa el desempeño final alcanzado. Ejemplo: [Piano](https://github.com/MCV-Univalle/Playtherapy/blob/c988e064259631f59331705f30ce55e2695f120b/Playtherapy/Assets/Scripts/Piano/GameManagerPiano.cs#L240-L243).

2. Los registros en la relación start_session son agregados mediante la función [addGameSession](https://github.com/MCV-Univalle/Playtherapy/blob/c988e064259631f59331705f30ce55e2695f120b/Playtherapy/Assets/Scripts/DAO/GameSessionController.cs#L14)(int score , float repititions, float time, int level , string minigame), que es usada en cada juego en el script GameManager o GameController, así: 
- [Piano](https://github.com/MCV-Univalle/Playtherapy/blob/c988e064259631f59331705f30ce55e2695f120b/Playtherapy/Assets/Scripts/Piano/GameManagerPiano.cs#L248-L254)
- [Topos](https://github.com/MCV-Univalle/Playtherapy/blob/c988e064259631f59331705f30ce55e2695f120b/Playtherapy/Assets/Scripts/Moles/GameManagerMoles.cs#L268-L272)
- [Rieles](https://github.com/MCV-Univalle/Playtherapy/blob/c988e064259631f59331705f30ce55e2695f120b/Playtherapy/Assets/Scripts/Rieles/GameManagerRieles.cs#L289-L313)
- [Baseball](https://github.com/MCV-Univalle/Playtherapy/blob/c988e064259631f59331705f30ce55e2695f120b/Playtherapy/Assets/Scripts/Baseball/GameController.cs#L465)
- [Figth](https://github.com/MCV-Univalle/Playtherapy/blob/c988e064259631f59331705f30ce55e2695f120b/Playtherapy/Assets/Scripts/Fight/GameControllerFight.cs#L395)
- [Figuras Mágicas](https://github.com/MCV-Univalle/Playtherapy/blob/c988e064259631f59331705f30ce55e2695f120b/Playtherapy/Assets/Scripts/Figuras%20Magicas/ManagerFM.cs#L262-L267)
- Tiro libre (no implementado en Manager)
- [Vecinos invasores](https://github.com/MCV-Univalle/Playtherapy/blob/c988e064259631f59331705f30ce55e2695f120b/Playtherapy/Assets/Scripts/Vecinos%20Invasores/ManagerVecinosInvasores.cs#L221-L225)
- El Gran Viaje (no implementado en Manager)
- [Guerra Medieval](https://github.com/MCV-Univalle/Playtherapy/blob/c988e064259631f59331705f30ce55e2695f120b/Playtherapy/Assets/Scripts/Guerra%20Medieval/GameManagerMedieval.cs#L265-L270)

**Comment by jpcv222** [comment]
Se propone enviar a la base de datos: 

1. Puntos buenos realizados
2. Porcentaje o desempeño calculado así: **(puntos buenos - puntos malos)/puntos totales * 100**

Validar propuesta

**Comment by jpcv222** [comment]
Se propone enviar a la base de datos:

1. Puntos buenos totales realizados.
2. Puntos totales realizados.

No es necesario guardar resultados de fórmulas como el porcentaje o desempeño.

**Comment by melissamillares** [comment]
Revisado.
