### ISSUE TITLE
Trabajar en las corecciones del paper

### ISSUE THREAD

**Issue by andresow** [MCV-Univalle/Playtherapy#180]
Realizar correcciones del paper *Advantages and Limitations of Using Leap Motion from a Developers, Physical
Therapists and Patients Perspective* relacionadas en [URL](https://docs.google.com/document/d/1nDtc6VkRcPLAgBzY_HT5lFcqka4FMHMlgXm0WErcNWQ/edit?usp=sharing).

**Comment by jpcv222** [comment]
Versiones del documento corregido disponibles en [URL](https://drive.google.com/open?id=1pdy6BHDhxQizXzF-wqywpc1Egbp0SInJ).
