### ISSUE TITLE
Consulta de goniometría de mano

### ISSUE THREAD

**Issue by mgcc05** [MCV-Univalle/Playtherapy#181]
Consulta de rangos articulares de la mano para la realización del Paper relacionado con el LeapMotion
[Exploración de mano](https://drive.google.com/open?id=1P2gB67pP7wJt9VYZxxbJcer5LLgHHbUX)
[Exploración de muñeca](https://drive.google.com/open?id=1P8nqdMTiPcRqzfp_z4fP9ywVScZ0Ur-9)
[Rangos de movimiento en miembro superior](https://drive.google.com/open?id=1PDAeryfMaAb-bEQDAy2WqMsrLrBLZh85)
[Goniometría de Claudio H. Taboadela](https://drive.google.com/open?id=1PG4VD4VX0uEVbvI5vxQ-gf0nh1m8khSn)

**Comment by melissamillares** [comment]
Revisado.
