### ISSUE TITLE
Leap Motion vídeo

### ISSUE THREAD

**Issue by jpcv222** [MCV-Univalle/Playtherapy#185]
Se debe grabar un vídeo en el que se observe claramente lo que captura el sensor Leap Motion cuando es utilizado. Para ello, se deberá utilizar Leap Motion Visualizer, y una aplicación para grabar los movimientos de la mano con una cámara web.

**Comment by jpcv222** [comment]
Vídeo disponible en: [Vídeo 1](https://cutt.ly/EyxjalH), [Vídeo 2](https://cutt.ly/pyxjKjP)

**Comment by melissamillares** [comment]
Revisado.
