### ISSUE TITLE
Integración back/front para registro y listado de diagnostico

### ISSUE THREAD

**Issue by andresow** [MCV-Univalle/Playtherapy#187]
Creado del tipo de diagnostico
![image.png](https://images.zenhubusercontent.com/5d14dd72b4a18a460a8e2f5d/7ff33261-4479-41c9-ac0a-937843888e7a)
![image.png](https://images.zenhubusercontent.com/5d14dd72b4a18a460a8e2f5d/51ab92bd-ab7d-42f2-b2ce-a3698123928e)

Listado
![image.png](https://images.zenhubusercontent.com/5d14dd72b4a18a460a8e2f5d/9e08fd41-5cd7-4dd6-ba1a-4dfd8d9ddf5c)

Se listan los tipo de diagnosticos en el select
![image.png](https://images.zenhubusercontent.com/5d14dd72b4a18a460a8e2f5d/783ad650-0f24-4fa4-9626-a54be954ff43)

Creacion
![image.png](https://images.zenhubusercontent.com/5d14dd72b4a18a460a8e2f5d/e41acf2d-2198-4cec-b28e-6c7d6d8eb55e)

Listado en el select de pacientes

![image.png](https://images.zenhubusercontent.com/5d14dd72b4a18a460a8e2f5d/5630d012-8820-4c7d-92f2-5a3d47b18a9f)

**Comment by franco026** [comment]
Reviaaso
