### ISSUE TITLE
Integración back/front para registro y listado de pacientes

### ISSUE THREAD

**Issue by andresow** [MCV-Univalle/Playtherapy#188]
Formulario con carga de entidades medicas en el select
![image.png](https://images.zenhubusercontent.com/5d14dd72b4a18a460a8e2f5d/8a9fcb10-b552-4f9c-9692-ec37b6c30708)

Formulario con carga de diagnósticos medicas en select
![image.png](https://images.zenhubusercontent.com/5d14dd72b4a18a460a8e2f5d/34ec0e7f-752b-43f5-b8db-6a0ce3a8b58d)

Envio
![image.png](https://images.zenhubusercontent.com/5d14dd72b4a18a460a8e2f5d/a74740ee-98ec-41eb-a989-90c4a06b38eb)

Listado(los espacios vacios en la tabla corresponden a  los botones que se agregaran)
![image.png](https://images.zenhubusercontent.com/5d14dd72b4a18a460a8e2f5d/30e78282-4d17-46bf-bfab-218d0495d4dc)

**Comment by franco026** [comment]
Revisado
