### ISSUE TITLE
Integracion back/front del loguin de la aplicacion.

### ISSUE THREAD

**Issue by andresow** [MCV-Univalle/Playtherapy#190]

**Comment by andresow** [comment]
![image.png](https://images.zenhubusercontent.com/5d14dd72b4a18a460a8e2f5d/6e95d6dc-e63b-49ed-a7f0-0698d7da3dac)

Una vez el usuario se logea, se notifica y se genera el token de acceso

**Comment by franco026** [comment]
Revisado
