### ISSUE TITLE
Regresar al menú del Playlist. 

### ISSUE THREAD

**Issue by jpcv222** [MCV-Univalle/Playtherapy#52]
No se puede regresar al menú Playlist una vez se ha seleccionado el juego. Debería poder regresar por algún medio.

**Comment by jpcv222** [comment]
[Video prueba](https://drive.google.com/open?id=1n9k4eWTvnN3V1wxymd-udlEhupj32Odl)

**Comment by melissamillares** [comment]
Revisado.
