### ISSUE TITLE
Cambio reloj por contador.

### ISSUE THREAD

**Issue by jpcv222** [MCV-Univalle/Playtherapy#54]
Cuando el juego se elije en modalidad de repeticiones, debería aparecer un contador de repeticiones y no un reloj.

**Comment by andresow** [comment]
1. Se muestran repeticiones.
2. Se cambia imagen de reloj por avión.
3. Se ajusta el tamaño. 

![image.png](https://images.zenhubusercontent.com/5d14dd72b4a18a460a8e2f5d/62a9ed70-f317-4158-8a8a-2c7b31ab0487)
