### ISSUE TITLE
Modo de juego por defecto.

### ISSUE THREAD

**Issue by jpcv222** [MCV-Univalle/Playtherapy#55]
Al ingresar a configurar el juego, en la pantalla de parámetros, no hay una configuración por defecto. Debería existir una configuración por defecto (modo de juego por defecto).

**Comment by jpcv222** [comment]
Para Figuras Mágicas: Ya se inicializan los parámetros con una configuración por defecto.

**Comment by melissamillares** [comment]
Adjuntar evidencia de la solución.

**Comment by jpcv222** [comment]
Figuras mágicas:
![image.png](https://images.zenhubusercontent.com/5d1d50c49c916c09a936e985/61e90f4e-3bcd-4869-9e7f-ecd1a44435bb)

Topos:
![image.png](https://images.zenhubusercontent.com/5d1d50c49c916c09a936e985/f9f966e6-d2f1-4209-a7c9-63d0fa3577c3)

**Comment by melissamillares** [comment]
Revisado.
