### ISSUE TITLE
Instrucciones para pantalla de parámetros.

### ISSUE THREAD

**Issue by jpcv222** [MCV-Univalle/Playtherapy#58]
Para el terapeuta no es claro lo que significa cada parámetro a configurar en el juego. A pesar de existir la especificación en la guía de usuario, se debe idear una estrategia para facilitar la comprensión de estas instrucciones en el juego.

**Comment by jpcv222** [comment]
Se propone adicionar tooltips

**Comment by melissamillares** [comment]
Adjuntar evidencia de la solución.

**Comment by jpcv222** [comment]
[Video prueba en piano](https://drive.google.com/open?id=1Mi2YTnewMLdmeLzj0TpdDXvQCu5ClnY2)
[Video prueba en topos](https://drive.google.com/open?id=1xbNdurhzaitSnNEHvWxQCzHldVMxjh_O)
