### ISSUE TITLE
Tiempo de descanso. 

### ISSUE THREAD

**Issue by jpcv222** [MCV-Univalle/Playtherapy#60]
Revisar rango de tiempo de descanso para el jugador entre repeticiones.

**Comment by jpcv222** [comment]
Tiempo de descanso entre repeticiones funcionando correctamente.

**Comment by andresow** [comment]
El tiempo de descanso esta dado en la distancia que demora en llegar la siguiente oleada de aviones, se adjunta evidencia de la distancia que este representa, con base a su configuracion
![image.png](https://images.zenhubusercontent.com/5d14dd72b4a18a460a8e2f5d/3c2a4c6c-d4d9-4142-908f-91d9a4882eca)
![image.png](https://images.zenhubusercontent.com/5d14dd72b4a18a460a8e2f5d/4616e60e-4476-411c-bed2-a1b0514006b3)

**Comment by melissamillares** [comment]
Revisado.
