### ISSUE TITLE
Corregir botón tutorial.

### ISSUE THREAD

**Issue by jpcv222** [MCV-Univalle/Playtherapy#61]
Botón para mostrar tutorial no funciona cuando se está en la pantalla de resultados.

**Comment by jpcv222** [comment]
Botón tutorial disponible únicamente desde pantalla de configuración de parámetros y pantalla de pausa. 
**Pantalla de configuración de parámetros**
![image.png](https://images.zenhubusercontent.com/5d1d50c49c916c09a936e985/a59c52d1-3954-4df1-9630-98561f8e3c9a)
**Pantalla de pausa**
![image.png](https://images.zenhubusercontent.com/5d1d50c49c916c09a936e985/4fd554bf-91a7-4a1c-b56b-e548304c90fc)
**Tutorial accedido desde pantalla de pausa**
![image.png](https://images.zenhubusercontent.com/5d1d50c49c916c09a936e985/a8763729-26af-45b3-82eb-a59308d8b2a3)

**Comment by franco026** [comment]
Revisado
