### ISSUE TITLE
Indicación visual para dibujar.

### ISSUE THREAD

**Issue by jpcv222** [MCV-Univalle/Playtherapy#66]
Al cerrar la mano, el juego deberá mostrar un lápiz (o alguna figura similar) con el fin de indicar al jugador que está en modo de dibujo.

**Comment by andresow** [comment]
Se realiza el cambio de Asest para que al realizar el dibujo se muestra que esta "dibujando"
![image.png](https://images.zenhubusercontent.com/5d14dd72b4a18a460a8e2f5d/34037c87-a8fe-428c-a825-df1d228e21aa)

**Comment by melissamillares** [comment]
Revisado.
