### ISSUE TITLE
Cambio de texto instrucciones. 

### ISSUE THREAD

**Issue by jpcv222** [MCV-Univalle/Playtherapy#67]
Se debe modificar el texto ubicado en la pantalla 3 del tutorial de juego, donde se indica que el movimiento o dibujo se realiza de "izquierda a derecha", pues los trazos son reconocidos en cualquier dirección.

**Comment by melissamillares** [comment]
Adjuntar evidencia de la solución.

**Comment by andresow** [comment]
![image.png](https://images.zenhubusercontent.com/5d14dd72b4a18a460a8e2f5d/dbba04da-364f-44ff-8cc4-f626ff99c29e)

**Comment by melissamillares** [comment]
Revisado.
