### ISSUE TITLE
Claridad de juego a configurar. 

### ISSUE THREAD

**Issue by jpcv222** [MCV-Univalle/Playtherapy#71]
En el Playlist no es claro cuál juego se configura actualmente. Una vez se da click en la pantalla de configuración, el selector de juego pierde el foco. Se debe asegurar que no se pierda el foco y garantizar que en la pantalla aparezca el nombre del juego.

**Comment by andresow** [comment]
Cada que selecciona el juego en cuestion se cambia el nombre del juego que se esta configurando
![image.png](https://images.zenhubusercontent.com/5d14dd72b4a18a460a8e2f5d/ffd3c900-e79c-47c9-a76e-d5a124d80d07)

**Comment by melissamillares** [comment]
Revisado.
