### ISSUE TITLE
Interferencia en sonido.

### ISSUE THREAD

**Issue by jpcv222** [MCV-Univalle/Playtherapy#89]
Sonido se distorsiona cuando se aproxima dispositivo móvil.
Se recomienda buscar forma para desactivar el micrófono del kinect en este juego.

**Comment by melissamillares** [comment]
Adjuntar evidencia de la solución

**Comment by jpcv222** [comment]
En Kinect Studio 2.0, se deben deshabilitar las opciones resaltadas en la siguiente imagen:  
![image.png](https://images.zenhubusercontent.com/5d1d50c49c916c09a936e985/a90ac0d1-8ca8-4600-9314-2b064cc95228)

**Comment by edwingamboa** [comment]
- [ ]  Se puede automatizar esto?
- [ ] Se encuentra escrito en el manual?
